spring:
  application:
    name: UcoChallenge

  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:ucochallenge}}"
    driver-class-name: "${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}"
    hikari:
      pool-name: "${SPRING_DATASOURCE_POOL_NAME:UcoHikariPool}"
      maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE:10}
      minimum-idle: ${SPRING_DATASOURCE_MIN_IDLE:1}
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    prefer-ip-address: true

azure:
  keyvault:
    url: "https://uco-vault-secrets.vault.azure.net/"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
      protocol: "http/protobuf"

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.azure.identity: INFO
    co.edu.uco.ucochallenge.infrastructure.secondary.secret: DEBUG
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"


services:
  message:
    base-url: "http://localhost:8082/api/v1/messages"
  parameters:
    base-url: "http://localhost:8083/api/v1/parameters"
