global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'parameters-service'
    scheme: https
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['parameters-service.onrender.com']

  - job_name: 'message-service'
    scheme: https
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['message-service-6kgu.onrender.com']

  - job_name: 'api-gateway'
    scheme: https
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway-server-xjsl.onrender.com']

  - job_name: 'eureka-server'
    scheme: https
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server-eureka-server-latest.onrender.com']